Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/node-sass/src/**/*'
    # - 'db/**/*'
    # - 'config/**/*'
    # - 'script/**/*'
    # - 'bin/{rails,rake}'
    # - !ruby/regexp /old_and_unused\.rb$/